#!/usr/bin/env python3
"""Assemble deck/index.html from modular sources under deck/src/.

Usage:
  python3 deck/build.py            # write index.html
  python3 deck/build.py --check    # exit 1 if index.html is stale
  python3 deck/build.py --watch    # rebuild when sources change
"""

from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path

DECK_DIR = Path(__file__).resolve().parent
SRC_DIR = DECK_DIR / "src"
SLIDES_DIR = SRC_DIR / "slides"
TEMPLATE_PATH = SRC_DIR / "template.html"
FRAMEWORK_CSS = SRC_DIR / "framework.css"
DECK_CSS = SRC_DIR / "deck.css"
DECK_JS = SRC_DIR / "deck.js"
OUTPUT_PATH = DECK_DIR / "index.html"

SECTION_RE = re.compile(r"<section\b", re.I)
SECTION_CLOSE_RE = re.compile(r"</section>", re.I)
SECTION_OPEN_RE = re.compile(r"<section\s+class=\"([^\"]*)\"", re.I)
FOOTER_PLACEHOLDER_RE = re.compile(r"\{\{N\}\}\s*/\s*\{\{TOTAL\}\}")
LABEL_RE = re.compile(r"\s*data-screen-label=\"[^\"]*\"")
ACTIVE_CLASS_RE = re.compile(r"(?:^|\s)active(?:\s|$)")


class BuildError(Exception):
    pass


def pad2(n: int) -> str:
    return f"{n:02d}"


def slug_to_label(stem: str) -> str:
    """01-cover -> Cover; 16-h0-h1 -> H0 H1; 27-prime-agent -> Prime Agent."""
    parts = stem.split("-", 1)
    if len(parts) != 2 or not parts[0].isdigit():
        raise BuildError(f"slide filename must be NN-slug.html, got {stem!r}")
    num, slug = parts
    words = []
    for word in slug.split("-"):
        if not word:
            continue
        if any(ch.isdigit() for ch in word):
            words.append(word.upper())
        else:
            words.append(word[:1].upper() + word[1:])
    return f"{num} {' '.join(words)}"


def list_slide_files() -> list[Path]:
    files = sorted(SLIDES_DIR.glob("*.html"))
    if not files:
        raise BuildError(f"no slide fragments in {SLIDES_DIR}")
    stems = [p.stem for p in files]
    if stems != sorted(stems):
        raise BuildError("slide filenames are not sorted lexicographically")
    return files


def prepare_slide(path: Path, index: int, total: int) -> str:
    raw = path.read_text(encoding="utf-8")
    opens = SECTION_RE.findall(raw)
    closes = SECTION_CLOSE_RE.findall(raw)
    if len(opens) != 1 or len(closes) != 1:
        raise BuildError(
            f"{path.name}: expected exactly one <section>…</section>, "
            f"found {len(opens)} open / {len(closes)} close"
        )

    # Drop any author-supplied label; the builder owns numbering/labels.
    raw = LABEL_RE.sub("", raw)

    m = SECTION_OPEN_RE.search(raw)
    if not m:
        raise BuildError(f"{path.name}: <section> must have a class attribute")

    classes = ACTIVE_CLASS_RE.sub(" ", m.group(1))
    classes = re.sub(r"\s+", " ", classes).strip()
    if "slide" not in classes.split():
        raise BuildError(f"{path.name}: section class must include 'slide'")
    if index == 1:
        classes = f"{classes} active".strip()

    label = slug_to_label(path.stem)
    rebuilt_open = f'<section class="{classes}" data-screen-label="{label}"'
    out = SECTION_OPEN_RE.sub(rebuilt_open, raw, count=1)

    n_ph = FOOTER_PLACEHOLDER_RE.findall(out)
    if len(n_ph) != 1:
        raise BuildError(
            f"{path.name}: footer must contain exactly one "
            f"'{{{{N}}}} / {{{{TOTAL}}}}' placeholder (found {len(n_ph)})"
        )
    out = FOOTER_PLACEHOLDER_RE.sub(f"{pad2(index)} / {pad2(total)}", out, count=1)
    return out.rstrip() + "\n"


def render() -> str:
    for required in (TEMPLATE_PATH, FRAMEWORK_CSS, DECK_CSS, DECK_JS, SLIDES_DIR):
        if not required.exists():
            raise BuildError(f"missing source: {required}")

    files = list_slide_files()
    total = len(files)
    prepared = [prepare_slide(path, i, total) for i, path in enumerate(files, start=1)]
    slides_html = "\n".join(prepared)

    template = TEMPLATE_PATH.read_text(encoding="utf-8")
    for key in ("{{FRAMEWORK_CSS}}", "{{DECK_CSS}}", "{{DECK_JS}}", "{{SLIDES}}"):
        if key not in template:
            raise BuildError(f"template missing slot {key}")

    framework = FRAMEWORK_CSS.read_text(encoding="utf-8").rstrip() + "\n"
    deck_css = DECK_CSS.read_text(encoding="utf-8").rstrip() + "\n"
    deck_js = DECK_JS.read_text(encoding="utf-8").rstrip() + "\n"

    banner = (
        "<!-- Generated by deck/build.py — edit sources under deck/src/, "
        "then re-run the builder. -->\n"
    )
    out = template
    out = out.replace("{{FRAMEWORK_CSS}}", framework.rstrip("\n"))
    out = out.replace("{{DECK_CSS}}", deck_css.rstrip("\n"))
    out = out.replace("{{DECK_JS}}", deck_js.rstrip("\n"))
    out = out.replace("{{SLIDES}}", slides_html.rstrip("\n"))
    if not out.startswith("<!doctype html>"):
        raise BuildError("rendered output missing doctype")
    if not out.endswith("\n"):
        out += "\n"
    return banner + out


def write_atomic(path: Path, content: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def build() -> str:
    content = render()
    write_atomic(OUTPUT_PATH, content)
    return content


def check() -> None:
    expected = render()
    if not OUTPUT_PATH.exists():
        raise BuildError(f"missing {OUTPUT_PATH} — run: python3 deck/build.py")
    actual = OUTPUT_PATH.read_text(encoding="utf-8")
    if actual != expected:
        raise BuildError(
            f"{OUTPUT_PATH.relative_to(DECK_DIR.parent)} is stale — "
            f"run: python3 deck/build.py"
        )


def source_fingerprint() -> tuple:
    paths = [TEMPLATE_PATH, FRAMEWORK_CSS, DECK_CSS, DECK_JS]
    paths.extend(list_slide_files())
    return tuple((str(p), p.stat().st_mtime_ns, p.stat().st_size) for p in paths)


def watch(poll_s: float = 0.4) -> None:
    print(f"watching {SRC_DIR} → {OUTPUT_PATH}", flush=True)
    last = None
    while True:
        try:
            fp = source_fingerprint()
            if fp != last:
                build()
                n = len(list_slide_files())
                print(f"built {OUTPUT_PATH.name} ({n} slides)", flush=True)
                last = fp
        except BuildError as exc:
            print(f"build error: {exc}", file=sys.stderr, flush=True)
            last = None
        except Exception as exc:  # noqa: BLE001 — keep watch alive
            print(f"unexpected error: {exc}", file=sys.stderr, flush=True)
            last = None
        time.sleep(poll_s)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if index.html is stale")
    mode.add_argument("--watch", action="store_true", help="rebuild on source changes")
    args = parser.parse_args(argv)

    try:
        if args.check:
            check()
            print(f"ok: {OUTPUT_PATH.name} is up to date")
            return 0
        if args.watch:
            watch()
            return 0
        build()
        n = len(list_slide_files())
        print(f"wrote {OUTPUT_PATH} ({n} slides)")
        return 0
    except BuildError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
